# Generated by Django 3.1.2 on 2020-11-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticiones',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='peticiones',
            name='usuario',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
