# Generated by Django 3.1.2 on 2020-11-01 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20201101_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peticiones',
        ),
    ]
