# Generated by Django 3.1.2 on 2020-11-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20201101_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
